# Seed data for Shathabdhi Organics
# All products, prices and images sourced directly from the live
# shathabdhiorganics.com Shopify catalogue.

products_seed = [
    # ============ MILLETS ============
    {"id": "m1", "name": "Foxtail Millet (Korralu)", "category": "Millets", "type": "Whole",
     "description": "Korra · Organic Whole Grain", "profile": "Nutty | Light | Versatile",
     "base_price": 60.0,
     "sizes": [{"size": "500 g", "price": 60.0}, {"size": "1 kg", "price": 115.0}, {"size": "2 kg", "price": 220.0}],
     "image": "https://cdn.shopify.com/s/files/1/0657/0832/6964/files/Foxtail_Millet_1.jpg?v=1724434250",
     "badge": "Best Seller", "benefits": ["Low GI", "High Fibre", "Gluten-Free"], "origin": "Telangana"},
    {"id": "m2", "name": "Little Millet (Samalu)", "category": "Millets", "type": "Whole",
     "description": "Samalu · Organic Whole Grain", "profile": "Mild | Quick Cooking | Protein Rich",
     "base_price": 90.0,
     "sizes": [{"size": "500 g", "price": 90.0}, {"size": "1 kg", "price": 170.0}, {"size": "2 kg", "price": 325.0}],
     "image": "https://cdn.shopify.com/s/files/1/0657/0832/6964/files/little_millet.webp?v=1723008970",
     "badge": "Siridhanya", "benefits": ["High Fibre", "Diabetic Friendly"], "origin": "Telangana"},
    {"id": "m3", "name": "Kodo Millet (Arikelu)", "category": "Millets", "type": "Whole",
     "description": "Arikelu / Arika · Organic Whole Grain", "profile": "Earthy | Fibre Packed | Nutritious",
     "base_price": 73.0,
     "sizes": [{"size": "500 g", "price": 73.0}, {"size": "1 kg", "price": 140.0}, {"size": "2 kg", "price": 270.0}],
     "image": "https://cdn.shopify.com/s/files/1/0657/0832/6964/files/Kodo_Millet.webp?v=1723008901",
     "badge": "Siridhanya", "benefits": ["High Fibre", "Gluten-Free"], "origin": "Telangana"},
    {"id": "m4", "name": "Barnyard Millet (Udalu)", "category": "Millets", "type": "Whole",
     "description": "Udalu / Kodisama · Organic Whole Grain", "profile": "Delicate | Iron Rich | Quick Cooking",
     "base_price": 85.0,
     "sizes": [{"size": "500 g", "price": 85.0}, {"size": "1 kg", "price": 160.0}, {"size": "2 kg", "price": 305.0}],
     "image": "https://cdn.shopify.com/s/files/1/0657/0832/6964/files/barnyard_millet.jpg?v=1724498783",
     "badge": "Siridhanya", "benefits": ["Iron Rich", "Diabetic Friendly", "Low GI"], "origin": "Telangana"},
    {"id": "m5", "name": "Brown Top Millet (Anda Korralu)", "category": "Millets", "type": "Whole",
     "description": "Anda Korralu · Organic Whole Grain", "profile": "Nutty | Wholesome | Delicate",
     "base_price": 155.0,
     "sizes": [{"size": "500 g", "price": 155.0}, {"size": "1 kg", "price": 300.0}],
     "image": "https://cdn.shopify.com/s/files/1/0657/0832/6964/files/brown_top_Millet_2.jpg?v=1724495011",
     "badge": "Siridhanya", "benefits": ["Low GI", "Gluten-Free"], "origin": "Telangana"},
    {"id": "m6", "name": "Pearl Millet (Sajjalu)", "category": "Millets", "type": "Whole",
     "description": "Sajjalu · Organic Whole Grain", "profile": "Robust | Hearty | Sustaining",
     "base_price": 48.0,
     "sizes": [{"size": "500 g", "price": 48.0}, {"size": "1 kg", "price": 90.0}, {"size": "2 kg", "price": 170.0}],
     "image": "https://cdn.shopify.com/s/files/1/0657/0832/6964/files/Pearl_Millet.webp?v=1723008749",
     "badge": "Best Seller", "benefits": ["High Fibre", "Iron Rich"], "origin": "Telangana"},
    {"id": "m7", "name": "Finger Millet (Ragulu)", "category": "Millets", "type": "Whole",
     "description": "Ragulu / Ragi · Organic Whole Grain", "profile": "Calcium Rich | Earthy | Versatile",
     "base_price": 58.0,
     "sizes": [{"size": "500 g", "price": 58.0}, {"size": "1 kg", "price": 110.0}, {"size": "2 kg", "price": 210.0}],
     "image": "https://cdn.shopify.com/s/files/1/0657/0832/6964/files/Finger_Millet.jpg?v=1724498834",
     "badge": "Best Seller", "benefits": ["Calcium Rich", "Gluten-Free", "Iron Rich"], "origin": "Telangana"},
    {"id": "m8", "name": "White Jowar (Jonnalu)", "category": "Millets", "type": "Whole",
     "description": "Jonnalu · Organic Sorghum", "profile": "Soft | Filling | Wholesome",
     "base_price": 55.0,
     "sizes": [{"size": "500 g", "price": 55.0}, {"size": "1 kg", "price": 105.0}, {"size": "2 kg", "price": 200.0}],
     "image": "https://cdn.shopify.com/s/files/1/0657/0832/6964/files/1_c03099e8-b252-4993-a6e8-a88afa252f2c.webp?v=1722854227",
     "badge": "Daily Essential", "benefits": ["High Fibre", "Gluten-Free"], "origin": "Telangana"},

    # ============ SPICES & POWDERS ============
    {"id": "s1", "name": "Turmeric Powder", "category": "Spices & Powders", "type": "Powder",
     "description": "Pasupu · Organic Spice Powder", "profile": "Warm | Earthy | Golden",
     "base_price": 76.0,
     "sizes": [{"size": "100 g", "price": 76.0}, {"size": "250 g", "price": 180.0}, {"size": "500 g", "price": 340.0}],
     "image": "https://cdn.shopify.com/s/files/1/0657/0832/6964/files/1_15e8b739-81fa-4831-96c8-ad3368bdbc6a.webp?v=1722854573",
     "badge": "Best Seller", "benefits": ["Anti-inflammatory"], "origin": "Telangana"},
    {"id": "s2", "name": "Chilli Powder", "category": "Spices & Powders", "type": "Powder",
     "description": "Karam Podi · Organic Spice Powder", "profile": "Spicy | Vibrant | Bold",
     "base_price": 210.0,
     "sizes": [{"size": "250 g", "price": 210.0}, {"size": "500 g", "price": 400.0}, {"size": "1 kg", "price": 780.0}],
     "image": "https://cdn.shopify.com/s/files/1/0657/0832/6964/files/1_8f225d66-10e7-4eca-bdcf-e4777e42206d.webp?v=1722853557",
     "badge": "Best Seller", "benefits": ["Metabolism Boost"], "origin": "Telangana"},
    {"id": "s3", "name": "Himalayan Pink Salt", "category": "Spices & Powders", "type": "Whole",
     "description": "Sendha Namak · Mineral Rich", "profile": "Mineral | Clean | Pure",
     "base_price": 85.0,
     "sizes": [{"size": "500 g", "price": 85.0}, {"size": "1 kg", "price": 160.0}],
     "image": "https://cdn.shopify.com/s/files/1/0657/0832/6964/files/1_444cecaa-12a9-48bb-8701-0c29af4072de.png?v=1722854051",
     "badge": "Pure", "benefits": ["Mineral Rich", "Iron Rich"], "origin": "Himalayas"},
    {"id": "s4", "name": "Brown Sugar", "category": "Spices & Powders", "type": "Whole",
     "description": "Unrefined Cane Sugar", "profile": "Caramel | Wholesome | Unrefined",
     "base_price": 120.0,
     "sizes": [{"size": "500 g", "price": 120.0}, {"size": "1 kg", "price": 230.0}],
     "image": "https://cdn.shopify.com/s/files/1/0657/0832/6964/files/1_a250ae70-3eba-4271-a17a-e417f32dcd03.webp?v=1722852874",
     "badge": "Unrefined", "benefits": ["Mineral Rich"], "origin": "Telangana"},
    {"id": "s5", "name": "Mustard Seeds", "category": "Spices & Powders", "type": "Whole",
     "description": "Aavalu · Organic Whole Seeds", "profile": "Pungent | Aromatic | Essential",
     "base_price": 42.0,
     "sizes": [{"size": "100 g", "price": 42.0}, {"size": "250 g", "price": 100.0}, {"size": "500 g", "price": 190.0}],
     "image": "https://cdn.shopify.com/s/files/1/0657/0832/6964/files/1_75636da3-c6be-464d-979b-51dc7cff9616.webp?v=1722856087",
     "badge": "Pantry Staple", "benefits": ["Digestive Aid"], "origin": "Telangana"},
    {"id": "s6", "name": "Jeera (Cumin Seeds)", "category": "Spices & Powders", "type": "Whole",
     "description": "Jeelakarra · Organic Whole Seeds", "profile": "Earthy | Warm | Aromatic",
     "base_price": 173.0,
     "sizes": [{"size": "100 g", "price": 173.0}, {"size": "250 g", "price": 410.0}, {"size": "500 g", "price": 790.0}],
     "image": "https://cdn.shopify.com/s/files/1/0657/0832/6964/files/jeera.jpg?v=1724433004",
     "badge": "Best Seller", "benefits": ["Digestive Aid"], "origin": "Telangana"},

    # ============ RICES ============
    {"id": "r1", "name": "Basmati Rice", "category": "Rices", "type": "Whole",
     "description": "Aged Long Grain · Organic", "profile": "Fragrant | Slender | Premium",
     "base_price": 225.0,
     "sizes": [{"size": "1 kg", "price": 225.0}, {"size": "5 kg", "price": 1080.0}],
     "image": "https://cdn.shopify.com/s/files/1/0657/0832/6964/files/basmathi_rice.jpg?v=1724496761",
     "badge": "Premium", "benefits": ["Aromatic"], "origin": "North India"},
    {"id": "r2", "name": "RNR Rice", "category": "Rices", "type": "Whole",
     "description": "RNR 15048 · Sona Quality", "profile": "Soft | Diabetic Friendly | Daily",
     "base_price": 125.0,
     "sizes": [{"size": "1 kg", "price": 125.0}, {"size": "5 kg", "price": 600.0}, {"size": "10 kg", "price": 1180.0}],
     "image": "https://cdn.shopify.com/s/files/1/0657/0832/6964/files/rnr_rice.jpg?v=1724497492",
     "badge": "Low GI", "benefits": ["Diabetic Friendly", "Low GI"], "origin": "Telangana"},
    {"id": "r3", "name": "Brown Rice", "category": "Rices", "type": "Whole",
     "description": "Unpolished · Wholegrain", "profile": "Nutty | High Fibre | Wholesome",
     "base_price": 120.0,
     "sizes": [{"size": "1 kg", "price": 120.0}, {"size": "5 kg", "price": 580.0}],
     "image": "https://cdn.shopify.com/s/files/1/0657/0832/6964/files/brown_rice.webp?v=1723008830",
     "badge": "High Fibre", "benefits": ["High Fibre", "Diabetic Friendly"], "origin": "Telangana"},
    {"id": "r4", "name": "Sona Masoori Rice", "category": "Rices", "type": "Whole",
     "description": "Aged · Light & Aromatic", "profile": "Light | Aromatic | Daily Staple",
     "base_price": 130.0,
     "sizes": [{"size": "1 kg", "price": 130.0}, {"size": "5 kg", "price": 620.0}, {"size": "10 kg", "price": 1220.0}],
     "image": "https://cdn.shopify.com/s/files/1/0657/0832/6964/files/1_e6b7ff17-fcfd-49d8-ae2e-4ce6d562430c.webp?v=1722855063",
     "badge": "Best Seller", "benefits": ["Light Digestion"], "origin": "Telangana"},

    # ============ OILS ============
    {"id": "o1", "name": "Sunflower Oil", "category": "Oils", "type": "Cold Pressed",
     "description": "Wood Pressed · Single Origin", "profile": "Light | Neutral | Heart Healthy",
     "base_price": 427.0,
     "sizes": [{"size": "1 L", "price": 427.0}, {"size": "5 L", "price": 2080.0}],
     "image": "https://cdn.shopify.com/s/files/1/0657/0832/6964/files/1_57e6957c-15a3-4ec5-b3ed-a54f30814344.webp?v=1722857652",
     "badge": "Cold Pressed", "benefits": ["Heart Healthy"], "origin": "Telangana"},
    {"id": "o2", "name": "Safflower Oil", "category": "Oils", "type": "Cold Pressed",
     "description": "Wood Pressed · Kusumalu", "profile": "Mild | Wholesome | Traditional",
     "base_price": 475.0,
     "sizes": [{"size": "1 L", "price": 475.0}, {"size": "5 L", "price": 2320.0}],
     "image": "https://cdn.shopify.com/s/files/1/0657/0832/6964/files/1_6b0def27-f129-4c15-8396-994c2f137a04.webp?v=1722855385",
     "badge": "Cold Pressed", "benefits": ["Heart Healthy"], "origin": "Telangana"},
    {"id": "o3", "name": "Groundnut Oil", "category": "Oils", "type": "Cold Pressed",
     "description": "Wood Pressed · Veru Senaga", "profile": "Rich | Nutty | Robust",
     "base_price": 430.0,
     "sizes": [{"size": "1 L", "price": 430.0}, {"size": "5 L", "price": 2100.0}],
     "image": "https://cdn.shopify.com/s/files/1/0657/0832/6964/files/1_a0537ee1-e46b-4f3a-9347-e52529053d6c.webp?v=1722859053",
     "badge": "Best Seller", "benefits": ["Vitamin E Rich"], "origin": "Telangana"},
    {"id": "o4", "name": "Sesame Oil", "category": "Oils", "type": "Cold Pressed",
     "description": "Wood Pressed · Nuvvulu", "profile": "Toasty | Aromatic | Ancient",
     "base_price": 585.0,
     "sizes": [{"size": "1 L", "price": 585.0}, {"size": "5 L", "price": 2860.0}],
     "image": "https://cdn.shopify.com/s/files/1/0657/0832/6964/files/1_1411dad8-2850-4957-a0e3-f8ee0d2921bc.webp?v=1722855206",
     "badge": "Premium", "benefits": ["Calcium Rich", "Antioxidant"], "origin": "Telangana"},
    {"id": "o5", "name": "Coconut Oil", "category": "Oils", "type": "Cold Pressed",
     "description": "Wood Pressed · Kobbari Nooni", "profile": "Sweet | Tropical | Multi-Purpose",
     "base_price": 850.0,
     "sizes": [{"size": "1 L", "price": 850.0}, {"size": "5 L", "price": 4150.0}],
     "image": "https://cdn.shopify.com/s/files/1/0657/0832/6964/files/1_8c643f4b-fff8-4d71-afce-f9e60f6fa0b3.webp?v=1722859357",
     "badge": "Premium", "benefits": ["Antioxidant"], "origin": "South India"},

    # ============ PROCESSED PRODUCTS ============
    {"id": "p1", "name": "Jowar Rich Multi-Grain Atta", "category": "Processed Products", "type": "Flour/Atta",
     "description": "Jonna Pindi Blend · Multi-Grain", "profile": "Wholesome | Soft Rotis | Nutritious",
     "base_price": 210.0,
     "sizes": [{"size": "1 kg", "price": 210.0}, {"size": "5 kg", "price": 1020.0}],
     "image": "https://cdn.shopify.com/s/files/1/0657/0832/6964/files/1_991ea35e-7ba5-4690-8cf3-a914b13a8552.webp?v=1722859648",
     "badge": "Family Favourite", "benefits": ["High Fibre", "Gluten-Free"], "origin": "Telangana"},
    {"id": "p2", "name": "Multi Millet Idly Rava", "category": "Processed Products", "type": "Ready-to-Cook",
     "description": "Steamed Breakfast Essential", "profile": "Soft | Fluffy | Quick",
     "base_price": 150.0,
     "sizes": [{"size": "500 g", "price": 150.0}, {"size": "1 kg", "price": 290.0}],
     "image": "https://cdn.shopify.com/s/files/1/0657/0832/6964/files/Idly_Rawa.webp?v=1723037466",
     "badge": "Breakfast", "benefits": ["High Fibre", "Easy Digestion"], "origin": "Telangana"},
    {"id": "p3", "name": "Foxtail Millet Pasta", "category": "Processed Products", "type": "Ready-to-Cook",
     "description": "Korralu Pasta · Modern Classic", "profile": "Al Dente | Wholesome | Quick",
     "base_price": 185.0,
     "sizes": [{"size": "200 g", "price": 185.0}, {"size": "500 g", "price": 440.0}],
     "image": "https://cdn.shopify.com/s/files/1/0657/0832/6964/files/1.Pasta-Front-Pic.webp?v=1721355404",
     "badge": "Modern Classic", "benefits": ["Low GI", "High Fibre"], "origin": "Telangana"},
    {"id": "p4", "name": "Jowar Iron Rich Vermicelli", "category": "Processed Products", "type": "Ready-to-Cook",
     "description": "Semiya · Sorghum Based", "profile": "Light | Iron Rich | Versatile",
     "base_price": 160.0,
     "sizes": [{"size": "200 g", "price": 160.0}, {"size": "500 g", "price": 380.0}],
     "image": "https://cdn.shopify.com/s/files/1/0657/0832/6964/files/1_84eef85b-d51d-42b2-a5a6-36b6fd24d22c.webp?v=1722856590",
     "badge": "Iron Rich", "benefits": ["Iron Rich", "Gluten-Free"], "origin": "Telangana"},

    # ============ DALS ============
    {"id": "d1", "name": "Toor Dal", "category": "Dals", "type": "Whole",
     "description": "Kandhi Pappu · Split Pigeon Pea", "profile": "Hearty | Daily Essential | Protein Rich",
     "base_price": 275.0,
     "sizes": [{"size": "1 kg", "price": 275.0}, {"size": "5 kg", "price": 1340.0}],
     "image": "https://cdn.shopify.com/s/files/1/0657/0832/6964/files/Toor_Dal.jpg?v=1724499452",
     "badge": "Daily Essential", "benefits": ["Protein Rich"], "origin": "Telangana"},
    {"id": "d2", "name": "Moong Dal", "category": "Dals", "type": "Whole",
     "description": "Pesara Pappu · Yellow Split", "profile": "Light | Easy Digestion | Nourishing",
     "base_price": 100.0,
     "sizes": [{"size": "500 g", "price": 100.0}, {"size": "1 kg", "price": 190.0}],
     "image": "https://cdn.shopify.com/s/files/1/0657/0832/6964/files/1_a3581c73-8895-4ceb-9a11-df745102caa4.webp?v=1722856289",
     "badge": "Light", "benefits": ["Protein Rich", "Easy Digestion"], "origin": "Telangana"},
    {"id": "d3", "name": "Chana Dal", "category": "Dals", "type": "Whole",
     "description": "Senaga Pappu · Split Chickpea", "profile": "Nutty | Robust | Versatile",
     "base_price": 75.0,
     "sizes": [{"size": "500 g", "price": 75.0}, {"size": "1 kg", "price": 145.0}],
     "image": "https://cdn.shopify.com/s/files/1/0657/0832/6964/files/1_8f2d8b99-56fb-4ef6-81e7-7b06d6d288ef.webp?v=1722853439",
     "badge": "Daily Essential", "benefits": ["Protein Rich", "High Fibre"], "origin": "Telangana"},
    {"id": "d4", "name": "Urad Dal", "category": "Dals", "type": "Whole",
     "description": "Minapa Pappu · Black Gram", "profile": "Creamy | Idly · Dosa | Traditional",
     "base_price": 220.0,
     "sizes": [{"size": "500 g", "price": 220.0}, {"size": "1 kg", "price": 420.0}],
     "image": "https://cdn.shopify.com/s/files/1/0657/0832/6964/files/1_f057302b-5749-4adb-97f5-1657a67c6615.webp?v=1722854411",
     "badge": "Traditional", "benefits": ["Protein Rich", "Iron Rich"], "origin": "Telangana"},

    # ============ COOKIES ============
    {"id": "c1", "name": "Jowar Cookies", "category": "Cookies", "type": "Ready-to-Eat",
     "description": "Sorghum Cookies · No Maida", "profile": "Crunchy | Wholesome | Tea-Time",
     "base_price": 80.0,
     "sizes": [{"size": "100 g · Pack of 5", "price": 80.0}],
     "image": "/products/jowar-cookies.jpg",
     "badge": "Best Seller", "benefits": ["No Refined Sugar"], "origin": "Telangana"},
    {"id": "c2", "name": "Jowar Almond Cookies", "category": "Cookies", "type": "Ready-to-Eat",
     "description": "Sorghum Almond Cookies", "profile": "Nutty | Crunchy | Wholesome",
     "base_price": 95.0,
     "sizes": [{"size": "100 g · Pack of 5", "price": 95.0}],
     "image": "/products/jowar-almond-cookies.jpg",
     "badge": "Best Seller", "benefits": ["No Refined Sugar"], "origin": "Telangana"},
    {"id": "c3", "name": "Jowar Choco Chip Cookies", "category": "Cookies", "type": "Ready-to-Eat",
     "description": "Sorghum Choco Chip · Kid Friendly", "profile": "Chocolatey | Crunchy | Family",
     "base_price": 80.0,
     "sizes": [{"size": "100 g · Pack of 5", "price": 80.0}],
     "image": "/products/jowar-choco-chip-cookies.jpg",
     "badge": "Kid Favourite", "benefits": ["No Refined Sugar"], "origin": "Telangana"},
    {"id": "c4", "name": "Assorted Jowar Cookies", "category": "Cookies", "type": "Ready-to-Eat",
     "description": "Variety Pack · Hand Baked", "profile": "Variety | Crunchy | Gift-Ready",
     "base_price": 190.0,
     "sizes": [{"size": "200 g", "price": 190.0}],
     "image": "/products/assorted-jowar-cookies.jpg",
     "badge": "Gift Pack", "benefits": ["No Refined Sugar"], "origin": "Telangana"},

    # ============ SNACKS & BARS ============
    {"id": "sb1", "name": "D-Lite Jowar Bar", "category": "Snacks & Bars", "type": "Ready-to-Eat",
     "description": "Sorghum Millet Bar · Pack of 10", "profile": "Crunchy | On-the-Go | Wholesome",
     "base_price": 200.0,
     "sizes": [{"size": "Pack of 10", "price": 200.0}],
     "image": "/products/d-lite-jowar-bar.jpg",
     "badge": "New", "benefits": ["No Refined Sugar", "High Fibre"], "origin": "Telangana"},
    {"id": "sb2", "name": "D-Lite Ragi Bar", "category": "Snacks & Bars", "type": "Ready-to-Eat",
     "description": "Finger Millet Bar · Pack of 10", "profile": "Calcium Rich | Energising | Hearty",
     "base_price": 200.0,
     "sizes": [{"size": "Pack of 10", "price": 200.0}],
     "image": "/products/d-lite-ragi-bar.jpg",
     "badge": "New", "benefits": ["Calcium Rich", "No Refined Sugar"], "origin": "Telangana"},
    {"id": "sb3", "name": "Mixed Millet Crisp", "category": "Snacks & Bars", "type": "Ready-to-Eat",
     "description": "Crunchy Multi-Millet Snack", "profile": "Crispy | Savoury | Family Snack",
     "base_price": 150.0,
     "sizes": [{"size": "250 g", "price": 150.0}],
     "image": "/products/mixed-millet-crisp.jpg",
     "badge": "Family Favourite", "benefits": ["High Fibre", "Multi-Grain"], "origin": "Telangana"},
    {"id": "sb4", "name": "Corn Murukulu", "category": "Snacks & Bars", "type": "Ready-to-Eat",
     "description": "Traditional Corn Murukku · Andhra Style", "profile": "Crispy | Spiced | Traditional",
     "base_price": 120.0,
     "sizes": [{"size": "130 g", "price": 120.0}],
     "image": "/products/corn-murukulu.jpg",
     "badge": "Traditional", "benefits": ["Hand-Made"], "origin": "Telangana"},
    {"id": "sb5", "name": "Mixed Millet Crisp Chocolate", "category": "Snacks & Bars", "type": "Ready-to-Eat",
     "description": "Chocolate-Coated Millet Crisp · Single Piece", "profile": "Indulgent | Crunchy | Bite-Size",
     "base_price": 25.0,
     "sizes": [{"size": "1 Piece", "price": 25.0}],
     "image": "/products/mixed-millet-crisp-chocolate.jpg",
     "badge": "Bite-Size", "benefits": ["No Refined Sugar"], "origin": "Telangana"},

    # ============ SWEETS & TREATS ============
    {"id": "st1", "name": "Ragi Chocos", "category": "Sweets & Treats", "type": "Ready-to-Eat",
     "description": "Finger Millet Breakfast Cereal · Choco", "profile": "Crunchy | Kid Friendly | Wholesome",
     "base_price": 145.0,
     "sizes": [{"size": "100 g", "price": 145.0}],
     "image": "/products/ragi-chocos.jpg",
     "badge": "Kid Friendly", "benefits": ["Calcium Rich", "Iron Rich"], "origin": "Telangana"},
    {"id": "st2", "name": "Ragi Laddu Box", "category": "Sweets & Treats", "type": "Ready-to-Eat",
     "description": "Hand-Rolled Ragi Laddus · 9 Pieces (~240 g)", "profile": "Earthy | Sweet | Festival-Ready",
     "base_price": 240.0,
     "sizes": [{"size": "9 Pieces", "price": 240.0}],
     "image": "/products/ragi-laddu-box.jpg",
     "badge": "Festive", "benefits": ["Calcium Rich", "No Refined Sugar"], "origin": "Telangana"},
    {"id": "st3", "name": "Jowar Muffin", "category": "Sweets & Treats", "type": "Ready-to-Eat",
     "description": "Soft Sorghum Muffin · Single Serve", "profile": "Soft | Fluffy | Tea-Time",
     "base_price": 25.0,
     "sizes": [{"size": "28 g", "price": 25.0}],
     "image": "/products/jowar-muffin.jpg",
     "badge": "Daily Snack", "benefits": ["No Refined Sugar"], "origin": "Telangana"},
    {"id": "st4", "name": "Ragi Muffin", "category": "Sweets & Treats", "type": "Ready-to-Eat",
     "description": "Soft Ragi Muffin · Single Serve", "profile": "Soft | Earthy | Tea-Time",
     "base_price": 25.0,
     "sizes": [{"size": "28 g", "price": 25.0}],
     "image": "/products/ragi-muffin.jpg",
     "badge": "Daily Snack", "benefits": ["Calcium Rich", "No Refined Sugar"], "origin": "Telangana"},

    # ============ HEALTH DRINKS ============
    {"id": "hd1", "name": "Millet Mix Cardamom", "category": "Health Drinks", "type": "Powder",
     "description": "Delicious Cardamom-flavoured Millet Drink Mix", "profile": "Warm | Fragrant | Comforting",
     "base_price": 350.0,
     "sizes": [{"size": "300 g", "price": 350.0}],
     "image": "/products/millet-mix-cardamom.jpg",
     "badge": "New", "benefits": ["High Fibre", "Calcium Rich", "Iron Rich"], "origin": "Telangana"},
    {"id": "hd2", "name": "Millet Mix Coffee Vanilla", "category": "Health Drinks", "type": "Powder",
     "description": "Delicious Coffee-Vanilla Millet Drink Mix", "profile": "Rich | Aromatic | Energising",
     "base_price": 276.0,
     "sizes": [{"size": "200 g", "price": 276.0}],
     "image": "/products/millet-mix-coffee-vanilla.jpg",
     "badge": "New", "benefits": ["High Fibre", "Iron Rich"], "origin": "Telangana"},
    {"id": "hd3", "name": "Millet Mix Coconut", "category": "Health Drinks", "type": "Powder",
     "description": "Delicious Coconut-flavoured Millet Drink Mix", "profile": "Tropical | Creamy | Smooth",
     "base_price": 206.0,
     "sizes": [{"size": "200 g", "price": 206.0}],
     "image": "/products/millet-mix-coconut.jpg",
     "badge": "New", "benefits": ["High Fibre", "Calcium Rich"], "origin": "Telangana"},
]

categories_seed = [
    {"id": "cat-1", "name": "Millets", "image": "https://cdn.shopify.com/s/files/1/0657/0832/6964/files/Foxtail_Millet_1.jpg?v=1724434250", "display_order": 1},
    {"id": "cat-2", "name": "Spices & Powders", "image": "https://cdn.shopify.com/s/files/1/0657/0832/6964/files/1_15e8b739-81fa-4831-96c8-ad3368bdbc6a.webp?v=1722854573", "display_order": 2},
    {"id": "cat-3", "name": "Rices", "image": "https://cdn.shopify.com/s/files/1/0657/0832/6964/files/basmathi_rice.jpg?v=1724496761", "display_order": 3},
    {"id": "cat-4", "name": "Oils", "image": "https://cdn.shopify.com/s/files/1/0657/0832/6964/files/1_57e6957c-15a3-4ec5-b3ed-a54f30814344.webp?v=1722857652", "display_order": 4},
    {"id": "cat-5", "name": "Processed Products", "image": "https://cdn.shopify.com/s/files/1/0657/0832/6964/files/1_991ea35e-7ba5-4690-8cf3-a914b13a8552.webp?v=1722859648", "display_order": 5},
    {"id": "cat-6", "name": "Dals", "image": "https://cdn.shopify.com/s/files/1/0657/0832/6964/files/Toor_Dal.jpg?v=1724499452", "display_order": 6},
    {"id": "cat-7", "name": "Cookies", "image": "https://cdn.shopify.com/s/files/1/0657/0832/6964/files/Jowar-Millet-Cookies-768x768.webp?v=1721349636", "display_order": 7},
    {"id": "cat-8", "name": "Snacks & Bars", "image": "https://images.unsplash.com/photo-1606312619070-d48b4c652a52?auto=format&fit=crop&w=800&q=80", "display_order": 8},
    {"id": "cat-9", "name": "Sweets & Treats", "image": "https://images.unsplash.com/photo-1606471191009-63994c53433b?auto=format&fit=crop&w=800&q=80", "display_order": 9},
    {"id": "cat-10", "name": "Health Drinks", "image": "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?auto=format&fit=crop&w=800&q=80", "display_order": 10},
]

testimonials_seed = [
    {"id": "t1", "name": "Priya Sharma",
     "text": "Best quality millets I've found! My family loves the Foxtail Millet. So fresh and nutritious.",
     "product_id": "m1", "product_name": "Foxtail Millet",
     "product_image": "https://cdn.shopify.com/s/files/1/0657/0832/6964/files/Foxtail_Millet_1.jpg?v=1724434250",
     "rating": 5, "is_featured": True},
    {"id": "t2", "name": "Rajesh Kumar",
     "text": "The turmeric powder is incredibly fresh and aromatic. You can tell it's pure and organic.",
     "product_id": "s1", "product_name": "Turmeric Powder",
     "product_image": "https://cdn.shopify.com/s/files/1/0657/0832/6964/files/1_15e8b739-81fa-4831-96c8-ad3368bdbc6a.webp?v=1722854573",
     "rating": 5, "is_featured": True},
    {"id": "t3", "name": "Anjali Reddy",
     "text": "Jowar Choco Chip Cookies are my kids' favourite — guilt-free indulgence that I trust.",
     "product_id": "c3", "product_name": "Jowar Choco Chip Cookies",
     "product_image": "https://cdn.shopify.com/s/files/1/0657/0832/6964/files/Jowar-Millet-Choco-Chip-768x768.webp?v=1721350116",
     "rating": 5, "is_featured": True},
    {"id": "t4", "name": "Venkat Rao",
     "text": "The cold-pressed sesame oil is exactly like the wood-pressed oils my grandmother used. Unmatched.",
     "product_id": "o4", "product_name": "Sesame Oil",
     "product_image": "https://cdn.shopify.com/s/files/1/0657/0832/6964/files/1_1411dad8-2850-4957-a0e3-f8ee0d2921bc.webp?v=1722855206",
     "rating": 5, "is_featured": True},
]
